-   id: azure-bicep-build
    name: build azure bicep code
    description: Build Azure Bicep code to check for validation errors
    language: script
    require_serial: true
    entry: hooks/azure-bicep-build.sh
    files: .*.bicep$