repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=2500]
  - id: check-merge-conflict
  - id: check-yaml
  - id: no-commit-to-branch
    args: [--branch, main]
- repo: https://github.com/Jake-Fawcett/azure-pre-commit-hooks
  rev: feature/bicep-build-files
  hooks:
    - id: azure-bicep-build
